apiVersion: v1
kind: Service
metadata:
  name: {{ include "servicematrix.fullname" . }}-postgres
  namespace: {{ include "servicematrix.namespace" . }}
  labels:
    {{- include "servicematrix.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "servicematrix.selectorLabels" (dict "root" . "component" "postgres") | nindent 4 }}
