apiVersion: v1
kind: Secret
metadata:
  name: {{ include "servicematrix.fullname" . }}-secrets
  namespace: {{ include "servicematrix.namespace" . }}
  labels:
    {{- include "servicematrix.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  secret-key: {{ .Values.backend.env.SECRET_KEY | required "backend.env.SECRET_KEY is required" | quote }}
  postgres-password: {{ .Values.postgres.env.POSTGRES_PASSWORD | required "postgres.env.POSTGRES_PASSWORD is required" | quote }}
  redis-password: {{ .Values.redis.password | required "redis.password is required" | quote }}
